services:
    helpdesk-api:
        image: ${IMAGE_NAME_API}
        container_name: ${CONTAINER_NAME_API}
        ports:
            - '${API_PORT:-3003}:3003'
        env_file:
            - .env.qa
        environment:
            - API_NODE_ENV=homolog
            - RUN_MIGRATIONS=true
            - RUN_SEEDS=true
        deploy:
            resources:
                limits:
                    memory: 1.5G
                reservations:
                    memory: 512M
        logging:
            driver: json-file
            options:
                max-size: '200m'
                max-file: '10'
        restart: unless-stopped
        networks:
            - helpdesk-network

    helpdesk-web:
        image: ${IMAGE_NAME_WEB}
        container_name: ${CONTAINER_NAME_WEB}
        ports:
            - '${WEB_PORT:-3004}:3004'
        env_file:
            - .env.qa
        depends_on:
            - helpdesk-api
        deploy:
            resources:
                limits:
                    memory: 2G
                reservations:
                    memory: 512M
        logging:
            driver: json-file
            options:
                max-size: '200m'
                max-file: '10'
        restart: unless-stopped
        networks:
            - helpdesk-network

networks:
    helpdesk-network:
        driver: bridge
